### ISSUE TITLE
Check

### ISSUE THREAD

**Issue by Effie375** [Effie375/PythonLab#116]
Check out all the exercises and examples.

**Comment by YodaCh96** [comment]
- [x] lab 02
- [ ] lab 03
- [ ] lab 04
- [ ] lab 05
- [ ] lab 06
- [ ] lab 07
- [ ] lab 08
- [ ] lab 09
- [ ] lab 10

**Comment by YodaCh96** [comment]
- Να προσαρμοστούν και τα αντίστοιχα md αρχεία.

**Comment by YodaCh96** [comment]
- [x] lecture 01
- [x] lecture 02
- [x] lecture 03
- [ ] lecture 04
- [ ] lecture 05
- [ ] lecture 06
- [ ] lecture 07
- [ ] lecture 08
- [ ] lecture 09
