### ISSUE TITLE
Στρογγυλοποίηση κατά μισή μονάδα πάνω ή κάτω

### ISSUE THREAD

**Issue by YodaCh96** [Effie375/PythonLab#58]
https://github.com/Effie375/PythonLab/blob/9fd623b314f198986880312bb55fe03620aba2f7/Laboratories/Lab_02_Exercise_1a.py#L6

**Comment by YodaCh96** [comment]
Το ίδιο και με την άσκηση **Lab_02_Exercise_1b**.

**Comment by Effie375** [comment]
[How to round to the nearest 0.5 in python?](https://www.reddit.com/r/learnprogramming/comments/542dk3/how_to_round_to_the_nearest_05_in_python/)
```python
print(round(x*2)/2)
```
